#!/bin/bash
echo "========================================="
echo " SDN Path Tracing Tool - Startup Guide"
echo "========================================="
echo ""
echo "TERMINAL 1 - Start controller:"
echo "  ryu-manager controller.py"
echo ""
echo "TERMINAL 2 - Start topology:"
echo "  sudo python3 topology.py"
echo ""
echo "TERMINAL 3 - After running 'pingall':"
echo "  sudo python3 path_tracer.py 10.0.0.1 10.0.0.2"
echo ""
echo "For firewall scenario, replace step 1 with:"
echo "  ryu-manager firewall.py"